export const SQL_SEMANTIC_CODES = {
    EXECUTION_FAILED: "SQL_EXECUTION_FAILED",
    RESULT_SHAPE_MISMATCH: "SQL_RESULT_SHAPE_MISMATCH",
    PROMPT_INTENT_MISMATCH: "SQL_PROMPT_INTENT_MISMATCH",
    DATASET_MISMATCH: "SQL_DATASET_MISMATCH",
    AGGREGATE_INTENT_MISMATCH: "SQL_AGGREGATE_INTENT_MISMATCH",
    JOIN_INTENT_MISMATCH: "SQL_JOIN_INTENT_MISMATCH",
} as const;