import type {TopicSeed} from "@zoeskoul/curriculum-contracts";
import type {SubjectShapePack} from "@zoeskoul/curriculum-profiles";
import {renderExercisePolicyPrompt} from "./renderExercisePolicyPrompt.js";
import { renderExerciseKindPromptRules } from "./exerciseKindPromptRules.js";
import type { TopicRetryContext } from "../types.js";


function renderRetryGuidance(retry?: TopicRetryContext) {
    if (!retry) return "";

    return [
        "",
        "IMPORTANT: This is a retry for the same topic.",
        `Retry attempt: ${retry.attempt} of ${retry.maxRetries}.`,
        `Previous failure code: ${retry.previousErrorCode}`,
        "Previous failure message:",
        retry.previousErrorMessage,
        "",
        "You must fix the issue above without changing the topic identity.",
        "Do not repeat the same validation mistake.",
        "",
        "If the failure mentions dummy fill_blank_choice questions:",
        "- Every fill_blank_choice must have a meaningful prompt.",
        "- Every template must contain real course-specific context.",
        "- Do not use placeholder templates like `The missing value is [blank1].`",
        "",
        "If the failure mentions generic exercise help:",
        "- Rewrite hints and help so they mention the exact question concept.",
        "",
        "If the failure mentions starterCode revealing solutionCode:",
        "- The previous starterCode was too complete.",
        "- Rewrite every failing code_input so starterCode is incomplete scaffolding only.",
        "- starterCode must not equal solutionCode after comments and whitespace are removed.",
        "- Keep the full runnable answer only in solutionCode.",
        "- Example for Python: starterCode can be `# Write your code below\\n`, while solutionCode contains the actual variables, expression, and print call.",
        "",
        "If the failure mentions workspace policy:",
        "- Do not mention files, .py filenames, terminals, command lines, package installation, or local workflows.",
        "",
        "If the failure mentions exercise policy targets or over target:",
        "- The previous draft used the wrong exercise-kind counts.",
        "- Regenerate quizDraft so each kind exactly matches the Required exercise counts.",
        "- Do not preserve the same total by replacing missing non-code exercises with extra code_input exercises.",
        "- If code_input is over target, remove extra code_input exercises and add the missing non-code exercise kinds.",
        "",
        "If the failure mentions INVALID_FILL_BLANK_STRUCTURE or multiple_blanks:",
        "- Regenerate the fill_blank_choice with exactly ONE blank.",
        "- Use only [blank1]. Do not use [blank2], [blank3], or multiple underscore blanks.",
        "- The template must contain one missing part and enough context to answer it.",
        "- Good example: `age = [blank1]` with choices `18`, `age`, `print`.",
        "- Good example: `[blank1] = 10` with choices `score`, `10`, `print`.",
        "- Bad example: `[blank1] = [blank2]`.",
        "- Bad example: `____ = ____`.",
    ].join("\n");
}
function renderWorkspacePolicy(seed: TopicSeed) {
    const policy = seed.workspacePolicy;
    if (!policy) return "";

    const c = policy.workspace.capabilities;
    const ui = policy.workspace.ui;

    return [
        "Learner workspace rules:",
        `- Workspace: ${policy.workspace.name}`,
        `- Editor label: ${ui.editorLabel ?? "editor"}`,
        `- Run button label: ${ui.runButtonLabel ?? "Run"}`,
        `- Output panel label: ${ui.outputPanelLabel ?? "output panel"}`,
        `- Terminal available: ${c.terminal.enabled ? "yes" : "no"}`,
        `- File creation available: ${c.filesystem.enabled ? "yes" : "no"}`,
        `- Multi-file projects available: ${c.multiFileProjects.enabled ? "yes" : "no"}`,
        `- Package installation available: ${c.packageInstall.enabled ? "yes" : "no"}`,
        "",
        "Preferred learner actions:",
        ...policy.preferredActionLanguage.map((x) => `- ${x}`),
        "",
        "Forbidden learner actions/language:",
        ...policy.forbiddenActionLanguage.map((x) => `- ${x}`),
        "",
        "Course notes:",
        ...policy.notes.map((x) => `- ${x}`),
    ].join("\n");
}
export function buildTopicAuthoringDraftPrompt(args: {
    seed: TopicSeed;
    locale: string;
    shape: SubjectShapePack;
    retry?: TopicRetryContext;
}) {
    const exercisePolicyRules = renderExercisePolicyPrompt({
        policy: args.seed.exercisePolicy,
        plannedCounts: args.seed.plannedExerciseCounts,
        generationTargets: args.seed.generationTargets,
    });
    const exerciseKindRules = renderExerciseKindPromptRules({
        mode: "authoring",
        seed: args.seed,
    });

    const sqlDatasetRules =
        args.seed.profileId === "sql"
            ? [
                "If profileId is sql:",
                "- use the moduleRuntimeDefaults.datasetId from the seed as the default dataset for the whole topic",
                "- all SQL examples in sketch bodyMarkdown must use tables and columns from the module dataset",
                "- sketches must never switch to an exercise dataset override",
                "- only code_input exercises may declare a datasetId override",
                "- if a code_input exercise overrides datasetId, that override applies only to that exercise runtime, not to sketches or other cards",
                "- do not invent table names or columns",
                "- do not use generic textbook placeholders like sales, products, product_name, or price unless they exist in the grounded schema",
                '- code_input recipeType must be "sql_query"',
                "- use only approved SQL datasetIds from the shape pack",
                "",
                "The seed also includes moduleDataset when available.",
                "Use its schema, table names, columns, and sample rows to design examples and exercises that fit the real dataset.",
                "",
                "For SQL relationship/join topics:",
                "- If the module dataset does not contain two related tables, do not generate SELECT JOIN code_input exercises.",
                "- If teaching relationships with a single-table dataset, use conceptual quiz questions or CREATE TABLE schema-design exercises with checkSql.",
                "- Never invent tables like orders, customers, enrollments, or order_items unless they exist in moduleDataset.schemaSql or the exercise itself creates them.",
                "- SQL code_input exercises that use SELECT do not need checkSql.",
                "- SQL code_input exercises that use INSERT, UPDATE, DELETE, REPLACE, CREATE, ALTER, or DROP should include checkSql.",
                "- checkSql must be a SELECT-style query that verifies the final database state after the statement runs.",
                "- For INSERT, checkSql should select the inserted row or final table state.",
                "- For UPDATE, checkSql should select the updated rows or final table state.",
                "- For DELETE, checkSql should select the final table state.",
                "- For CREATE TABLE or ALTER TABLE, checkSql can query sqlite_master to verify the table definition.",
            ]
            : [];

    return {
        system: [
            "You generate a TopicAuthoringDraft JSON object for ZoeSkoul.",
            "Return JSON only.",
            "Do not wrap the result in markdown.",
            "Do not generate topic.bundle.json directly.",
            "Do not generate subject.manifest.json directly.",
            "Do not generate filesystem paths.",
            "Use the provided shape pack as the contract.",
            "IMPORTANT: quizDraft items are AUTHORING items, not final manifest exercises.",
            "Do not use fields like purpose, weight, messageBase, optionIds, or expected.",
            "Instead use content fields like title, prompt, options, correctOptionIds, starterCode, solutionCode, template, choices, correctValue, tokens, correctOrder.",
            "",
            "Every exercise must include a real solution.",
            "Do not leave any solution field empty.",
            "",
            renderRetryGuidance(args.retry),

            "The top-level object must contain exactly:",
            '- "title"',
            '- "summary"',
            '- "minutes"',
            '- "sketchBlocks"',
            '- "quizDraft"',
            '- optional "projectDraft"',
            "",
            "Every sketchBlocks item must contain exactly:",
            '- "id"',
            '- "title"',
            '- "bodyMarkdown"',
            "",
            "Teaching-quality rules for sketchBlocks in every subject:",
            "- Include at least one concrete worked example, not just abstract definitions.",
            "- Explain the main idea clearly in beginner-friendly language.",
            "- Include a short learner action such as 'Try it yourself', 'Try this', or 'Your turn' whenever the topic can support it.",
            "",
            "Extra teaching rules for programming-family profiles:",
            "- Show at least one fenced code example in sketchBlocks.",
            "- If a code example spans multiple lines, explain it step by step or line by line.",
            "- Include a small 'Try it yourself' follow-up that invites the learner to modify, run, or extend the example.",
            "",
            "Every quizDraft item must ALWAYS contain:",
            '- "id"',
            '- "kind"',
            '- "title"',
            '- "prompt"',
            '- "hint"',
            '- "help"',
            "",
            'The "help" object must ALWAYS contain exactly:',
            '- "concept"',
            '- "hint_1"',
            '- "hint_2"',
            "",
            "Writing rule for support fields:",
            "- concept = explain the specific underlying idea for this exact question.",
            "- hint = shortest specific nudge tied to this exact question.",
            "- hint_1 = stronger specific hint that points to the relevant concept, syntax, input/output behavior, or misconception.",
            "- hint_2 = strongest specific hint before the answer, but still not the final answer.",
            "",
            "Support fields must be specific, not generic.",
            "Do not use vague test-taking language such as:",
            "- Focus on the main concept.",
            "- Choose the option that matches the core idea.",
            "- Eliminate choices that describe something different.",
            "- Build the solution from the behavior being tested.",
            "- Think about the role or idea being tested.",
            "",
            "For a question about Python use cases, a good hint is: 'Think about tasks where Python can automate repeated steps or process data.'",
            "For a question about the browser runner, a good hint is: 'Look for the answer that uses the editor, Run button, and output panel.'",
            "For a question about print output, a good hint is: 'Check exactly what print sends to the output panel, including spaces and punctuation.'",
            "",
            "Do not reveal the exact final answer in hint, hint_1, or hint_2.",
            "Do not give the final SQL query, final option letter, or final exact filled value in hints.",
            "For code_input, hints may describe the target behavior, intermediate reasoning, or relevant inputs, but not the final full solution.",
            "",
            ...exerciseKindRules,
            "",
            "Strict fill_blank_choice rules:",
            "- Each fill_blank_choice template must contain exactly ONE blank marker.",
            "- Use `[blank1]` exactly once.",
            "- Do not use `[blank2]`, `[blank3]`, or any second blank marker.",
            "- Do not use multiple underscore blanks such as `____ = ____`.",
            "- Do not create templates where both the variable name and value are missing.",
            "- The template must include enough context to answer the one missing part.",
            "- For variable-assignment topics, choose only ONE missing part:",
            "  Good: `[blank1] = 10` with choices like `age`, `name`, `print`.",
            "  Good: `age = [blank1]` with choices like `10`, `age`, `print`.",
            "  Bad: `[blank1] = [blank2]`.",
            "  Bad: `____ = ____`.",
            "- The `correctValue` must be exactly the value that fills `[blank1]`.",
            "- The choices must include the correctValue and plausible distractors.",
            "",
            "Publishing rule:",
            "- code_input authoring items are published as project practice automatically.",
            "- single_choice, multi_choice, drag_reorder, and fill_blank_choice are published as quiz practice.",
            "- You may include projectDraft, but the compiler will also create a project card automatically for code_input exercises.",
            "",
            ...sqlDatasetRules,
            "",
            exercisePolicyRules,
            "",
            "If projectDraft is present:",
            '- it must contain "title" and "stepIds"',
            "- every stepId must refer to an existing quizDraft item id",
            "",
            "Final self-check before returning JSON:",
            "- Every exercise kind matches the number of correct answers it needs.",
            "- Every multi_choice includes ALL correct options, not only one.",
            "- Every fill_blank_choice has exactly one blank and exactly one correctValue.",
            "- Every code_input follows the profile-specific runtime and recipe rules.",
            "Python code_input recipe rules:",
            '- For normal beginner output exercises, set recipeType to "fixed_tests" and include tests[].',
            '- For class, object, method, attribute, return-value, or structure-checking exercises, set recipeType to "semantic" and include semanticChecks[].',
            '- If recipeType is "semantic", do not rely on stdout tests.',
            '- If recipeType is "fixed_tests", include at least one stdin/stdout test.',
            '- Never leave recipeType ambiguous for Python code_input exercises.',
            "- Hints explain the concept but do not reveal the final answer wording.",
            "- Sketch SQL examples must use the module dataset, not an exercise dataset.",
            renderWorkspacePolicy(args.seed),
        ].join("\n"),
        user: JSON.stringify(
            {
                locale: args.locale,
                seed: args.seed,
                shape: args.shape,
            },
            null,
            2,
        ),
    };
}
