import type {TopicSeed} from "@zoeskoul/curriculum-contracts";
import type {SubjectShapePack} from "@zoeskoul/curriculum-profiles";
import {renderExercisePolicyPrompt} from "./renderExercisePolicyPrompt.js";

export function buildTopicAuthoringDraftPrompt(args: {
    seed: TopicSeed;
    locale: string;
    shape: SubjectShapePack;
}) {
    const exercisePolicyRules = renderExercisePolicyPrompt({
        policy: args.seed.exercisePolicy,
        plannedCounts: args.seed.plannedExerciseCounts,
    });

    const sqlDatasetRules =
        args.seed.profileId === "sql"
            ? [
                "If profileId is sql:",
                "- use the moduleRuntimeDefaults.datasetId from the seed as the default dataset for the whole topic",
                "- all SQL examples in sketch bodyMarkdown must use tables and columns from the module dataset",
                "- sketches must never switch to an exercise dataset override",
                "- only code_input exercises may declare a datasetId override",
                "- if a code_input exercise overrides datasetId, that override applies only to that exercise runtime, not to sketches or other cards",
                "- do not invent table names or columns",
                "- do not use generic textbook placeholders like sales, products, product_name, or price unless they exist in the grounded schema",
                '- code_input recipeType must be "sql_query"',
                "- use only approved SQL datasetIds from the shape pack",
                "",
                "The seed also includes moduleDataset when available.",
                "Use its schema, table names, columns, and sample rows to design examples and exercises that fit the real dataset.",
                "",
                "For SQL relationship/join topics:",
                "- If the module dataset does not contain two related tables, do not generate SELECT JOIN code_input exercises.",
                "- If teaching relationships with a single-table dataset, use conceptual quiz questions or CREATE TABLE schema-design exercises with checkSql.",
                "- Never invent tables like orders, customers, enrollments, or order_items unless they exist in moduleDataset.schemaSql or the exercise itself creates them.",
                "- SQL code_input exercises that use SELECT do not need checkSql.",
                "- SQL code_input exercises that use INSERT, UPDATE, DELETE, REPLACE, CREATE, ALTER, or DROP should include checkSql.",
                "- checkSql must be a SELECT-style query that verifies the final database state after the statement runs.",
                "- For INSERT, checkSql should select the inserted row or final table state.",
                "- For UPDATE, checkSql should select the updated rows or final table state.",
                "- For DELETE, checkSql should select the final table state.",
                "- For CREATE TABLE or ALTER TABLE, checkSql can query sqlite_master to verify the table definition.",
            ]
            : [];

    return {
        system: [
            "You generate a TopicAuthoringDraft JSON object for ZoeSkoul.",
            "Return JSON only.",
            "Do not wrap the result in markdown.",
            "Do not generate topic.bundle.json directly.",
            "Do not generate subject.manifest.json directly.",
            "Do not generate filesystem paths.",
            "Use the provided shape pack as the contract.",
            "IMPORTANT: quizDraft items are AUTHORING items, not final manifest exercises.",
            "Do not use fields like purpose, weight, messageBase, optionIds, or expected.",
            "Instead use content fields like title, prompt, options, correctOptionIds, starterCode, solutionCode, template, choices, correctValue, tokens, correctOrder.",
            "",
            "Every exercise must include a real solution.",
            "For single_choice, include exactly one correctOptionId.",
            "For multi_choice, include one or more correctOptionIds.",
            "For drag_reorder, include the full correctOrder.",
            "For fill_blank_choice, include a non-empty correctValue and make sure it exactly matches one of choices.",
            "For code_input, include non-empty solutionCode.",
            "For non-SQL code_input, include a tests array with one or more stdin/stdout cases.",
            "For non-SQL code_input, write a complete runnable program that reads from standard input when needed and prints the final answer.",
            "Do not leave any solution field empty.",
            "",
            "The top-level object must contain exactly:",
            '- "title"',
            '- "summary"',
            '- "minutes"',
            '- "sketchBlocks"',
            '- "quizDraft"',
            '- optional "projectDraft"',
            "",
            "Every sketchBlocks item must contain exactly:",
            '- "id"',
            '- "title"',
            '- "bodyMarkdown"',
            "",
            "Teaching-quality rules for sketchBlocks in every subject:",
            "- Include at least one concrete worked example, not just abstract definitions.",
            "- Explain the main idea clearly in beginner-friendly language.",
            "- Include a short learner action such as 'Try it yourself', 'Try this', or 'Your turn' whenever the topic can support it.",
            "",
            "Extra teaching rules for programming-family profiles:",
            "- Show at least one fenced code example in sketchBlocks.",
            "- If a code example spans multiple lines, explain it step by step or line by line.",
            "- Include a small 'Try it yourself' follow-up that invites the learner to modify, run, or extend the example.",
            "",
            "Every quizDraft item must ALWAYS contain:",
            '- "id"',
            '- "kind"',
            '- "title"',
            '- "prompt"',
            '- "hint"',
            '- "help"',
            "",
            'The "help" object must ALWAYS contain exactly:',
            '- "concept"',
            '- "hint_1"',
            '- "hint_2"',
            "",
            "Writing rule for support fields:",
            "- concept = explain the underlying idea clearly",
            "- hint = shortest nudge",
            "- hint_1 = stronger hint",
            "- hint_2 = strongest hint before the answer",
            "",
            "Do not reveal the exact final answer in hint, hint_1, or hint_2.",
            "Do not give the final SQL query, final option letter, or final exact filled value in hints.",
            "For code_input, hints may mention the target columns, operator family, or dataset logic, but not the final full solution query.",
            "For non-SQL code_input, hints may describe the behavior to implement, but not the final full program.",
            "",
            "For kind = single_choice or multi_choice, include:",
            '- "options"',
            '- "correctOptionIds"',
            "",
            "For kind = fill_blank_choice:",
            "- Use exactly one blank only.",
            "- Do not create two or more blanks in the same exercise.",
            "- The template must contain exactly one placeholder.",
            "- If the concept needs two answers, split it into two exercises or use a different kind.",
            "",
            "For kind = multi_choice:",
            "- Use multi_choice only when 2 or more options are genuinely correct.",
            "- Include every correct option in correctOptionIds, not just one example correct answer.",
            "- If only one option is correct, use single_choice instead.",
            '- When the prompt says "Select all that apply", "Choose all that apply", "Which are true", "Which scenarios", "Which of the following are", or similar plural wording, strongly prefer 2 or more correct options when appropriate.',
            "- Do not default to a single correct answer for multi_choice.",
            "- Before returning JSON, audit the full options list and include ALL correct options in correctOptionIds.",
            "- If option a, b, and d are all correct, correctOptionIds must be exactly [\"a\", \"b\", \"d\"].",
            "- Never stop after finding the first correct option.",
            "- Double-check the incorrect options too, so no true option is omitted and no false option is included.",
            "",
            "For kind = drag_reorder, include:",
            '- "tokens"',
            '- "correctOrder"',
            "",
            "For kind = fill_blank_choice, include:",
            '- "template"',
            '- "choices"',
            '- "correctValue"',
            "",
            "For kind = code_input, include:",
            '- "starterCode"',
            '- "solutionCode"',
            '- optional "tests" as an array of { stdin?, stdout, match? } for non-SQL code_input',
            '- optional "datasetId"',
            '- optional "recipeType"',
            '- optional "checkSql" for SQL mutation statements',
            "",
            "Publishing rule:",
            "- code_input authoring items are published as project practice automatically.",
            "- single_choice, multi_choice, drag_reorder, and fill_blank_choice are published as quiz practice.",
            "- You may include projectDraft, but the compiler will also create a project card automatically for code_input exercises.",
            "",
            ...sqlDatasetRules,
            "",
            "If profileId is not sql:",
            '- prefer code_input recipeType "fixed_tests"',
            "- include at least one real stdin/stdout test case for every code_input exercise",
            "- make solutionCode compatible with those tests as a full runnable program",
            "",
            exercisePolicyRules,
            "",
            "If projectDraft is present:",
            '- it must contain "title" and "stepIds"',
            "- every stepId must refer to an existing quizDraft item id",
            "",
            "Final self-check before returning JSON:",
            "- Every exercise kind matches the number of correct answers it needs.",
            "- Every multi_choice includes ALL correct options, not only one.",
            "- Every fill_blank_choice has exactly one blank and exactly one correctValue.",
            "- Every code_input has the required SQL datasetId when recipeType is sql_query.",
            "- Every non-SQL code_input includes real tests with expected stdout.",
            "- Hints explain the concept but do not reveal the final answer wording.",
            "- Sketch SQL examples must use the module dataset, not an exercise dataset.",
        ].join("\n"),
        user: JSON.stringify(
            {
                locale: args.locale,
                seed: args.seed,
                shape: args.shape,
            },
            null,
            2,
        ),
    };
}
