import type { TopicSeed } from "@zoeskoul/curriculum-contracts";
import type { SubjectShapePack } from "@zoeskoul/curriculum-profiles";

export function buildTopicAuthoringDraftPrompt(args: {
    seed: TopicSeed;
    locale: string;
    shape: SubjectShapePack;
}) {
    const sqlDatasetRules =
        args.seed.profileId === "sql"
            ? [
                "If profileId is sql:",
                "- use the moduleRuntimeDefaults.datasetId from the seed as the default dataset for the whole topic",
                "- all SQL code_input exercises must use that dataset unless an explicit override is requested",
                "- all SQL examples in sketch bodyMarkdown must use table names and columns that belong to that same dataset",
                "- do not invent table names or columns from another dataset",
                "- do not mix datasets inside one topic unless explicitly instructed",
                '- code_input recipeType must be "sql_query"',
                "- use only approved SQL datasetIds from the shape pack",
                "",
                "The seed also includes moduleDataset when available.",
                "Use its schema, table names, columns, and sample rows to design examples and exercises that fit the real dataset.",
            ]
            : [];

    return {
        system: [
            "You generate a TopicAuthoringDraft JSON object for ZoeSkoul.",
            "Return JSON only.",
            "Do not wrap the result in markdown.",
            "Do not generate topic.bundle.json directly.",
            "Do not generate subject.manifest.json directly.",
            "Do not generate filesystem paths.",
            "Use the provided shape pack as the contract.",
            "IMPORTANT: quizDraft items are AUTHORING items, not final manifest exercises.",
            "Do not use fields like purpose, weight, messageBase, optionIds, or expected.",
            "Instead use content fields like title, prompt, options, correctOptionIds, starterCode, solutionCode, template, choices, correctValue, tokens, correctOrder.",
            "",
            "Every exercise must include a real solution.",
            "For single_choice, include exactly one correctOptionId.",
            "For multi_choice, include one or more correctOptionIds.",
            "For drag_reorder, include the full correctOrder.",
            "For fill_blank_choice, include a non-empty correctValue.",
            "For code_input, include non-empty solutionCode.",
            "Do not leave any solution field empty.",
            "",
            "The top-level object must contain exactly:",
            '- "title"',
            '- "summary"',
            '- "minutes"',
            '- "sketchBlocks"',
            '- "quizDraft"',
            '- optional "projectDraft"',
            "",
            "Every sketchBlocks item must contain exactly:",
            '- "id"',
            '- "title"',
            '- "bodyMarkdown"',
            "",
            "Every quizDraft item must ALWAYS contain:",
            '- "id"',
            '- "kind"',
            '- "title"',
            '- "prompt"',
            '- "hint"',
            '- "help"',
            "",
            'The "help" object must ALWAYS contain exactly:',
            '- "concept"',
            '- "hint_1"',
            '- "hint_2"',
            "",
            "Writing rule for support fields:",
            "- concept = explain the underlying idea clearly",
            "- hint = shortest nudge",
            "- hint_1 = stronger hint",
            "- hint_2 = strongest hint before the answer",
            "",
            "Do not reveal the exact final answer in hint, hint_1, or hint_2.",
            "Do not give the final SQL query, final option letter, or final exact filled value in hints.",
            "For code_input, hints may mention the target columns, operator family, or dataset logic, but not the final full solution query.",
            "",
            "For kind = single_choice or multi_choice, include:",
            '- "options"',
            '- "correctOptionIds"',
            "",
            "For kind = drag_reorder, include:",
            '- "tokens"',
            '- "correctOrder"',
            "",
            "For kind = fill_blank_choice, include:",
            '- "template"',
            '- "choices"',
            '- "correctValue"',
            "",
            "For kind = code_input, include:",
            '- "starterCode"',
            '- "solutionCode"',
            '- optional "datasetId"',
            '- optional "recipeType"',
            "",
            ...sqlDatasetRules,
            "",
            "If projectDraft is present:",
            '- it must contain "title" and "stepIds"',
            "- every stepId must refer to an existing quizDraft item id",
        ].join("\n"),
        user: JSON.stringify(
            {
                locale: args.locale,
                seed: args.seed,
                shape: args.shape,
            },
            null,
            2,
        ),
    };
}