services:
  caddy:
    image: caddy:2
    container_name: edge-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy

volumes:
  caddy_data:
  caddy_config:

networks:
  public:
    external: true
