#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_DIR="$INFRA_DIR/env"
PROD_ENV="$ENV_DIR/production.env"
JUDGE0_ENV="$ENV_DIR/judge0.env"

mkdir -p "$ENV_DIR"

rand_hex() {
  openssl rand -hex "${1:-32}"
}

uid_now="$(id -u)"
gid_now="$(id -g)"
rootless_socket="/run/user/${uid_now}/docker.sock"
if [[ -S "$rootless_socket" ]]; then
  socket_gid="$(stat -c '%g' "$rootless_socket")"
else
  socket_gid="$gid_now"
fi

if [[ -f "$PROD_ENV" ]]; then
  echo "Exists: $PROD_ENV"
else
  POSTGRES_PASSWORD="$(rand_hex 24)"
  AUTH_SECRET="$(rand_hex 32)"
  REDIS_PASSWORD="$(rand_hex 24)"
  RUNNER_SHARED_SECRET="$(rand_hex 32)"
  PTY_ATTACH_SECRET="$(rand_hex 32)"
  RUNNER_EDGE_SECRET="$(rand_hex 32)"
  JUDGE0_EDGE_SECRET="$(rand_hex 32)"

  cat > "$PROD_ENV" <<EOF_INNER
COMPOSE_PROJECT_NAME=zoeskoul
BACKEND_NETWORK=zoeskoul-backend
EDGE_WEB_NETWORK=zoeskoul-edge-web
EDGE_RUNNER_NETWORK=zoeskoul-edge-runner
JUDGE0_NETWORK=zoeskoul-judge0-internal

POSTGRES_IMAGE=postgres:16.8
REDIS_IMAGE=redis:7.4-alpine
CADDY_IMAGE=caddy:2.9.1
WEB_IMAGE=zoeskoul-web:preview
RUNNER_SERVICE_IMAGE=zoeskoul-runner:preview
RUNTIME_IMAGE=zoeskoul-runtime:preview

POSTGRES_USER=zoeskoul
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=zoeskoul
DATABASE_URL=postgresql://zoeskoul:$POSTGRES_PASSWORD@postgres:5432/zoeskoul
REDIS_PASSWORD=$REDIS_PASSWORD
REDIS_URL=redis://:$REDIS_PASSWORD@redis:6379

NODE_ENV=production
WEB_PORT=3000
NEXTAUTH_URL=https://zoeskoul.com
AUTH_SECRET=$AUTH_SECRET

CADDY_WEB_SITE=https://zoeskoul.com
CADDY_RUNNER_SITE=https://runner.zoeskoul.com
CADDY_JUDGE0_SITE=https://judge0.zoeskoul.com
WEB_UPSTREAM=web:3000
RUNNER_UPSTREAM=runner:4001
JUDGE0_UPSTREAM=judge0:2358
RUNNER_EDGE_SECRET=$RUNNER_EDGE_SECRET
JUDGE0_EDGE_SECRET=$JUDGE0_EDGE_SECRET

RUNNER_BASE_URL=http://runner:4001
RUNNER_WS_BASE_URL=wss://runner.zoeskoul.com

# Hardened default: runner uses rootless Docker, not /var/run/docker.sock.
RUNNER_DOCKER_MODE=rootless
RUNNER_DOCKER_SOCKET_HOST=$rootless_socket
RUNNER_DOCKER_SOCKET_IN_CONTAINER=/run/runner-docker/docker.sock
RUNNER_DOCKER_SOCKET_GID=$socket_gid
RUNNER_CONTAINER_USER=$uid_now:$gid_now
ALLOW_ROOT_DOCKER_SOCKET=0

RUNNER_WORKSPACE_ROOT=/var/lib/zoeskoul/runner-workspaces
RUNNER_SHARED_SECRET=$RUNNER_SHARED_SECRET
PTY_ATTACH_SECRET=$PTY_ATTACH_SECRET
PTY_ATTACH_TOKEN_TTL_SECONDS=60
PTY_ATTACH_REPLAY_TTL_MS=300000
RUN_WALL_TIMEOUT_MS=15000
RUN_IDLE_TIMEOUT_MS=20000
RUNNER_EXEC_UID=1000
RUNNER_EXEC_GID=1000
RUNNER_MAX_FILES=32
RUNNER_MAX_TOTAL_BYTES=262144
RUNNER_MAX_FILE_BYTES=65536
RUNNER_MAX_ENTRIES=200
RUNNER_MAX_CONCURRENT_PER_ACTOR=3
RUNNER_MAX_CONCURRENT_GLOBAL=40
RUNNER_STARTS_PER_MINUTE_PER_ACTOR=12
RUNNER_CHILD_NETWORK=none
RUNNER_DISABLE_NETWORK=1
RUNNER_MEMORY_LIMIT_MB=128
RUNNER_CPU_QUOTA=50000
RUNNER_PIDS_LIMIT=128
RUNNER_MIN_FREE_BYTES=1073741824
RUNNER_MAX_WORKSPACE_ROOT_BYTES=5368709120
RUNNER_SERVICE_MEM_LIMIT=512m
RUNNER_SERVICE_CPUS=1.0

RUNNER_HOST_BIND=127.0.0.1
RUNNER_HOST_PORT=4001

BACKUP_DIR=/var/backups/zoeskoul/postgres
BACKUP_RETENTION_DAYS=14
EOF_INNER
  chmod 600 "$PROD_ENV"
  echo "Created: $PROD_ENV"
fi

if [[ -f "$JUDGE0_ENV" ]]; then
  echo "Exists: $JUDGE0_ENV"
else
  JUDGE0_POSTGRES_PASSWORD="$(rand_hex 24)"
  JUDGE0_REDIS_PASSWORD="$(rand_hex 24)"
  JUDGE0_AUTHN_TOKEN="$(rand_hex 32)"
  JUDGE0_AUTHZ_TOKEN="$(rand_hex 32)"
  cat > "$JUDGE0_ENV" <<EOF_INNER
JUDGE0_IMAGE=judge0/judge0:1.13.1
JUDGE0_POSTGRES_IMAGE=postgres:16.8
JUDGE0_REDIS_IMAGE=redis:7.4-alpine
JUDGE0_POSTGRES_USER=judge0
JUDGE0_POSTGRES_PASSWORD=$JUDGE0_POSTGRES_PASSWORD
JUDGE0_POSTGRES_DB=judge0
JUDGE0_REDIS_PASSWORD=$JUDGE0_REDIS_PASSWORD
JUDGE0_RAILS_ENV=production
JUDGE0_ENABLE_WAIT_RESULT=true
JUDGE0_DISABLE_MEMORY_LIMIT=false
JUDGE0_AUTHN_HEADER=X-Judge0-Token
JUDGE0_AUTHN_TOKEN=$JUDGE0_AUTHN_TOKEN
JUDGE0_AUTHZ_HEADER=X-Judge0-Admin
JUDGE0_AUTHZ_TOKEN=$JUDGE0_AUTHZ_TOKEN
JUDGE0_ALLOW_ORIGIN=http://localhost
JUDGE0_ENABLE_COMPILER_OPTIONS=false
JUDGE0_ENABLE_COMMAND_LINE_ARGUMENTS=false
JUDGE0_ENABLE_SUBMISSION_DELETE=false
JUDGE0_ENABLE_BATCHED_SUBMISSIONS=false
JUDGE0_ENABLE_CALLBACKS=false
JUDGE0_MAX_QUEUE_SIZE=50
JUDGE0_CPU_TIME_LIMIT=2
JUDGE0_MAX_CPU_TIME_LIMIT=5
JUDGE0_WALL_TIME_LIMIT=5
JUDGE0_MAX_WALL_TIME_LIMIT=10
JUDGE0_MEMORY_LIMIT=128000
JUDGE0_MAX_MEMORY_LIMIT=256000
JUDGE0_STACK_LIMIT=64000
JUDGE0_MAX_STACK_LIMIT=128000
JUDGE0_MAX_FILE_SIZE=1024
JUDGE0_MAX_PROCESSES_AND_OR_THREADS=64
JUDGE0_API_MEM_LIMIT=2g
JUDGE0_WORKER_MEM_LIMIT=3g
JUDGE0_API_CPUS=2.0
JUDGE0_WORKER_CPUS=2.0
JUDGE0_HOST_BIND=127.0.0.1
JUDGE0_HOST_PORT=2358
EOF_INNER
  chmod 600 "$JUDGE0_ENV"
  echo "Created: $JUDGE0_ENV"
fi

echo "Next: ./scripts/install-rootless-docker.sh, then ./scripts/preflight.sh"
