import type { WorkspaceProfile } from "@zoeskoul/curriculum-contracts";

export const WORKSPACE_PROFILES: Record<string, WorkspaceProfile> = {
    "browser-code-runner": {
        id: "browser-code-runner",
        name: "Browser code runner",
        ui: {
            editorLabel: "code editor",
            runButtonLabel: "Run",
            outputPanelLabel: "output panel",
            feedbackPanelLabel: "feedback area",
            terminalPanelLabel: null,
            filesPanelLabel: null,
        },
        capabilities: {
            singleFileCodeInput: { enabled: true },
            multiFileProjects: { enabled: false },
            terminal: { enabled: false },
            filesystem: { enabled: false },
            stdinStdout: { enabled: true },
            packageInstall: { enabled: false },
            externalNetwork: { enabled: false },
            uploads: { enabled: false },
            createFiles: { enabled: false },
            createFolders: { enabled: false },
        },
        preferredActionLanguage: [
            "Type code in the code editor.",
            "Click Run.",
            "Check the output panel.",
            "Compare the output with the expected output."
        ],
        forbiddenActionLanguage: [
            "Create a file",
            "Save this as",
            "Open a terminal",
            "Use the command line",
            "Run python file.py",
            "Install a package",
            "Use pip",
            "Create multiple files"
        ],
    },

    "browser-python-files-runner": {
        id: "browser-python-files-runner",
        name: "Browser Python files runner",
        ui: {
            editorLabel: "code editor",
            runButtonLabel: "Run",
            outputPanelLabel: "output panel",
            feedbackPanelLabel: "feedback area",
            terminalPanelLabel: null,
            filesPanelLabel: "files panel",
        },
        capabilities: {
            singleFileCodeInput: { enabled: true },
            multiFileProjects: { enabled: true },
            terminal: { enabled: false },
            filesystem: { enabled: true },
            stdinStdout: { enabled: true },
            packageInstall: { enabled: false },
            externalNetwork: { enabled: false },
            uploads: { enabled: false },
            createFiles: {
                enabled: true,
                label: "Create file",
                notes: "Learners can create files in the online editor file explorer when the lesson asks for it.",
            },
            createFolders: {
                enabled: true,
                label: "Create folder",
                notes: "Learners can create folders in the online editor file explorer when the lesson asks for it.",
            },
        },
        preferredActionLanguage: [
            "Open the provided file in the files panel.",
            "Create files or folders in the files panel only when the lesson explicitly asks for it.",
            "Use nested file paths such as data/input.txt or src/main.py when the lesson provides folders.",
            "Edit Python code in the code editor.",
            "Click Run.",
            "Check the output panel.",
        ],
        forbiddenActionLanguage: [
            "Open a terminal",
            "Use the command line",
            "Install a package",
            "Use pip",
            "Use external files not provided by the lesson",
        ],
    },

    "browser-sql-runner": {
        id: "browser-sql-runner",
        name: "Browser SQL runner",
        ui: {
            editorLabel: "SQL editor",
            runButtonLabel: "Run query",
            resultsTableLabel: "results table",
            outputPanelLabel: "results panel",
            feedbackPanelLabel: "feedback area",
            terminalPanelLabel: null,
            filesPanelLabel: null,
        },
        capabilities: {
            singleFileCodeInput: { enabled: true },
            multiFileProjects: { enabled: false },
            terminal: { enabled: false },
            filesystem: { enabled: false },
            stdinStdout: { enabled: false },
            packageInstall: { enabled: false },
            externalNetwork: { enabled: false },
            uploads: { enabled: false },
            createFiles: { enabled: false },
            createFolders: { enabled: false },
            sql: {
                queryRunner: { enabled: true },
                resultsTable: { enabled: true },
                schemaBrowser: { enabled: true },
                erdDiagram: { enabled: true },
                chenDiagram: { enabled: true },
            },
        },
        preferredActionLanguage: [
            "Write the query in the SQL editor.",
            "Click Run query.",
            "Check the results table.",
            "Use the schema, ERD, or Chen diagram when the lesson asks you to inspect relationships."
        ],
        forbiddenActionLanguage: [
            "Open a terminal",
            "Use the command line",
            "Install a database",
            "Create a local SQL file",
            "Run a shell command"
        ],
    },

    "full-ide": {
        id: "full-ide",
        name: "Full IDE workspace",
        ui: {
            editorLabel: "editor",
            runButtonLabel: "Run",
            outputPanelLabel: "output panel",
            terminalPanelLabel: "terminal",
            filesPanelLabel: "file explorer",
        },
        capabilities: {
            singleFileCodeInput: { enabled: true },
            multiFileProjects: { enabled: true },
            terminal: { enabled: true },
            filesystem: { enabled: true },
            stdinStdout: { enabled: true },
            packageInstall: { enabled: true },
            externalNetwork: { enabled: false },
            uploads: { enabled: true },
            createFiles: {
                enabled: true,
                label: "Create file",
            },
            createFolders: {
                enabled: true,
                label: "Create folder",
            },
        },
        preferredActionLanguage: [
            "Open files in the file explorer.",
            "Create files or folders in the file explorer when the lesson asks for it.",
            "Use nested paths such as src/main.py, data/input.txt, or tests/test_main.py when helpful.",
            "Edit the code in the editor.",
            "Click Run or use the terminal if the lesson asks for it.",
            "Check the output panel or terminal output.",
        ],
        forbiddenActionLanguage: [],
    },
    "terminal-workspace-runner": {
        id: "terminal-workspace-runner",
        name: "Terminal workspace runner",
        ui: {
            editorLabel: "terminal",
            runButtonLabel: "terminal command",
            outputPanelLabel: "terminal output",
            feedbackPanelLabel: "feedback area",
            terminalPanelLabel: "terminal",
            filesPanelLabel: "file explorer",
        },
        capabilities: {
            singleFileCodeInput: { enabled: true },
            multiFileProjects: { enabled: true },
            terminal: {
                enabled: true,
                label: "Terminal",
                notes: "Learners complete tasks by typing shell commands in the workspace terminal.",
            },
            filesystem: {
                enabled: true,
                label: "Workspace filesystem",
                notes: "Learners create, move, copy, rename, remove, and inspect files inside the lesson workspace.",
            },
            stdinStdout: { enabled: true },
            packageInstall: { enabled: false },
            externalNetwork: { enabled: false },
            uploads: { enabled: false },
            createFiles: {
                enabled: true,
                label: "Create file",
                notes: "Learners create files with terminal commands such as touch, cp, mv, or shell redirection.",
            },
            createFolders: {
                enabled: true,
                label: "Create folder",
                notes: "Learners create folders with terminal commands such as mkdir and mkdir -p.",
            },
        },
        preferredActionLanguage: [
            "Use the terminal to complete the task.",
            "Type Linux commands at the prompt.",
            "Use pwd and ls to inspect the current workspace.",
            "Use mkdir, touch, cp, mv, rm, cat, head, tail, or wc only when the lesson asks for them.",
            "Check the terminal output and file explorer.",
            "Click Check Answer when the workspace matches the goal.",
        ],
        forbiddenActionLanguage: [
            "Use sudo",
            "Install packages",
            "Use external network access",
            "Change system directories",
            "Use rm -rf /",
            "Leave the lesson workspace",
            "Edit hidden solution files",
        ],
    },

};
